spring:
  application:
    name: sshare
  profiles: development

  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://173.249.37.118/sshare_test
    driver-class-name: com.mysql.jdbc.Driver
    hikari:
      idle-timeout: 10000

  jpa:
    hibernate:
      ddl-auto: update

  sshare:
    file-store:
        path: /Users/alexander_ustinov/data
    jwt-config:
      jwt-secret: JWTSuperSecretKey
      jwt-expiration-in-ms: 604800000

server:
  port: 8080